### ISSUE TITLE
CalibreLibgenStore-0.3.zip is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by loopion** [fallaciousreasoning/CalibreLibgenStore#3]
Hello,

Don't know if I'm the only one to have this error when loading the plugin but I keep getting this error.
I've also tried to unistall and reinstall it and to package it myself but it doesn't work. 

Any idea?

`calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/johndoe/Downloads/CalibreLibgenStore-0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Libgen Fiction (0, 1, 0) && The Eye (0, 1, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/Users/johndoe/Downloads/CalibreLibgenStore-0.3.zip' is invalid. It does not contain a top-level __init__.py file
`

Thanks

**Comment by toma12** [comment]
Hi,
I have the same issue as @loopion.


calibre, version 4.23.0
Грешка:  Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/home/username/Desktop/CalibreLibgenStore-0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: bg
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'/home/username/Desktop/CalibreLibgenStore-0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by fallaciousreasoning** [comment]
Yeah, sorry, I uploaded the wrong file. This should be fixed now.

https://github.com/fallaciousreasoning/CalibreLibgenStore/releases/tag/v0.3
